// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;
using SQLiteNetExtensions.Attributes;
using SQLite.Net.Attributes;

namespace TBA.Models
{

    public class DistrictListModel
    {
        [Indexed, PrimaryKey]
        public string PK { get; set; }

        [JsonProperty("key")]
        [Indexed]
        public string Key { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [OneToMany(CascadeOperations = CascadeOperation.All)]
        public List<EventModel> DistrictEvents { get; set; }
    }

}