// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;

namespace TBA.Models
{

    public class EventsResponse
    {
        public bool IsSuccessful { get; set; }
        public EventModel Data { get; set;}
        public Exception Exception { get; set; }
    }
}
