// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
using SQLite.Net.Attributes;

namespace TBA.Models
{

    public class TeamModel
    {
        [JsonProperty("key")]
        [Indexed, PrimaryKey]
        public string Key { get; set; }

        [JsonProperty("website")]
        public string Website { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("locality")]
        public string Locality { get; set; }

        [JsonProperty("rookie_year")]
        public int? RookieYear { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("team_number")]
        public int TeamNumber { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("country_name")]
        public string CountryName { get; set; }

        [JsonProperty("motto")]
        public string Motto { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }
    }

}
